---
create_user: david
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.davidpeachme.pub') }}"
certbot_email: "mail@davidpeach.co.uk"
sys_packages: [ 'curl', 'vim', 'git', 'ufw', 'nginx', 'certbot', 'python3-certbot-nginx' ]
http_host: "davidpeach.me"
http_conf: "davidpeach.me.conf"
http_port: "80"
