---
create_user: david
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519_zet.pub') }}"
certbot_email: "mail@davidpeach.me"
sys_packages: [ 'curl', 'vim', 'git', 'ufw', 'nginx', 'certbot', 'python3-certbot-nginx' ]
http_host: "davidpeach.me"
http_conf: "davidpeach.me.conf"
http_host_zet: "zet.davidpeach.me"
http_conf_zet: "zet.davidpeach.me.conf"
http_port: "80"
